- src/components/UserPage/UserPage.jsx
Created the UserPage folder and file.
> starting th user page

- src/components/HomePage/HomePage.jsx
Added temporary <h1> heading as a placeholder for the Home Page layout.
> Start Home Page Structure

- src/components/BrowseAdventuresPage/BrowseAdventuresPage.jsx
This Pull Request is for the addition of the BrowseAdventuresPage component.
> Added BrowseAdventuresPage to file structure

- src/components/HeroSection/HeroSection.jsx
- src/components/HomePage/HomePage.jsx
- src/components/HowItWorksSection/HowItWorksSection.jsx
- src/components/RecentActivitySection/RecentActivitySection.jsx
Added <section> tags to HeroSection, HowItWorksSection, and RecentActivitySection to keep structure organized.
> Add section structure to HomePage Components

- src/components/EditForm/EditForm.jsx
edit adventure form modal sample. this is just to practice a pull request. feel free to delete any code in the component.
> Edit adventure form

- server/modules/pool.js
- src/components/App/App.jsx
- src/components/BrowseAdventuresPage/BrowseAdventures.css
- src/components/BrowseAdventuresPage/BrowseAdventuresPage.jsx
Created individual divs for containers for each component that will be added to the BrowseAdventuresPage.
> added containers for BrowseAdventuresPage

- src/components/HeroSection/HeroSection.jsx
- src/components/HowItWorksSection/HowItWorksSection.jsx
- src/components/RecentActivitySection/RecentActivitySection.jsx
-Created HeroSection with three CTAs and a scroll-down arrow.
-Created HowItWorksSection with two cards and a map placeholder.
-Created RecentActivitySection as a stub ready for backend data.
-Imported all sections into HomePage.jsx so the layout renders correctly.
> feat(homepage): created Hero, HowItWorks, and RecentActivity sections

- sampleData.sql
updated adventure table with correct references, added category table, cost table, ability table, and favorite adventures table. also added sample data for each table.
> Sample sql data

- src/components/AboutUs/AboutUs.jsx
- src/components/HomePage/HomePage.jsx
- Implemented HomePage.jsx with HeroSection, HowItWorksSection, and RecentActivitySection components
- Removed test user info and log out button for a cleaner homepage
- Set up the main homepage structure for the app
> Feature: Build and clean up HomePage component

- src/components/AboutUs/AboutUs.jsx
- Created About.jsx as a standalone component for the About page.
- Moved the About content out of App.jsx
- Updated App.jsx to use the new About component in routing.
> Add About page as a standalone component

- src/components/AddAdventure/AddAdventure.jsx
- src/components/ContactUs/ContactUs.jsx
- src/components/MyAdventuresViews/MyAdventuresViews.jsx
- src/components/NewsletterSignUp/NewsletterSignUp.jsx
- src/components/PendingAdventure/PendingAdventure.jsx
- Added placeholder React component files for upcoming main pages:
- MyAdventuresView.jsx
- PendingAdventure.jsx
- AddAdventure.jsx
- ContactUs.jsx
- NewsletterSignUp.jsx
- Each file contains a basic functional component as a scaffold for future development
- This setup allows team members to work on their assigned pages without breaking routes or imports
> Create placeholder component files for main pages

- index.html
Pull Request for title changing Prime Solo Project to Outdoor Adeventures. 
No Impact - Just updates the title present on the browser tab
> Updated title for Outdoor Adventures in the index.html file

- server/modules/pool.js
- server/routes/adventure.router.js
i added the. post route on the adventures route, but we still need to update the user (created_by) id as it was hard code with the number 1.
> added the post route

- package.json
- server/routes/adventure.router.js
- src/components/AddressSearch/AddressSearch.jsx
- added AddressSearch component 
- search bar with address autocomplete and address options drop-down
- search button that searches for existing adventures in a 20 mile radius of the address selected 
- google maps component that shows the adventures within 20 miles as pins on the map
- router.get route to get adventures in a certain radius 
WORKING ON NOW (IN PROGRESS)
- filters to filter adventures by category, difficulty, price
- update sql query to only show adventures with the status of "accepted"
- search bar component for adding adventures that allows users to have address autocomplete in the AddAdventureForm
> Address search component using google maps

- server/routes/adventure.router.js
Added put route, charlotte helped with the last part which is the id.
> added the put route

- server/routes/adventure.router.js
- src/components/AddressSearch/AddressSearch.jsx
- src/components/AutoCompleteInput/AutoCompleteInput.jsx
- src/components/StaticMap/StaticMap.jsx
AddressSearch component
- Search bar with autocomplete to search for adventures in a 20 mile radius of selected address
- pinpoints on map of valid adventure locations
- as of now it contains a .map to map out adventures that meet criteria. this can be changed to an adventure card component in the future.
- (backend) get route for adventures in 20 mile radius with the status of "accepted"
- *IN PROGRESS* filters for category, price, difficulty
StaticMap component
- draggable map with satellite view, street view, google maps standard view
AutoCompleteInput component
- Input bar with address autocomplete using google maps "places" api
- this is a reusable component that can be used anywhere there is an input with address autocomplete required.
- *IN PROGRESS* still working on latitude and …
> added AddressSearch component, StaticMap component, AutoCompleteInput component.

- sampleData.sql
(hopefully) final database update.
> Sql database update

- src/components/AddAdventure/AddAdventure.jsx
- src/components/App/App.jsx
Updated the /add-adventure route in App.jsx to point to the AddAdventureForm component
> Feature: AddAdventureForm route setup

- src/components/HeroSection/HeroSection.jsx
- Added React Router Link to the “Add Your Own Adventure” card in HeroSection.jsx
> Feature: Added AddAdventureForm link in HeroSection

- package.json
- server/routes/adventure.router.js
updated PUT route with updated DB
> updated PUT

- src/components/App/App.jsx
This PR corrects the import path for the AddAdventureForm component in App.jsx, moving it from ../AddAdventure/AddAdventureForm to ../AddAdventureForm/AddAdventureForm to match the actual folder structure.
> Fix AddAdventureForm import path in App.jsx

- src/components/LoginPage/LoginPage.css
- src/components/LoginPage/LoginPage.jsx
- src/index.css
Small adjustments to the login styling to update the button appearances. Added an additional class name to the jsx file as well
> adjusted button styling for login

- src/components/App/App.jsx
-Removed the duplicate <header> and <footer> blocks from App.jsx
-Relies on the existing Nav component to render both header and footer layout
> chore(App.jsx): remove duplicate header and footer (Nav now handles layout)

- src/components/AddressSearch/AddressSearch.jsx
- src/components/BrowseAdventuresPage/BrowseAdventuresPage.jsx
- src/components/HowItWorksSection/HowItWorksSection.jsx
added empty css file to AddressSearch component. added AddressSearch component to BrowseAdventurespage. It will just need to be styled.
> Google maps

- src/components/HomePage/HomePage.jsx
-Removed the unused useStore import from HomePage.jsx
-Removed user info and logout code blocks for HomePage.jsx
> chore(HomePage): remove unused user store import and user info code

- server/routes/adventure.router.js
UPDATE:
working on the post, hopefully to be finished soon.
> Jorges branch

- src/components/AddAdventureForm/AddAdventureForm.css
Just some little css adjustments
> Minor adjustments to the form spacing

- src/components/HowItWorksSection/HowItWorksSection.css
- src/components/HowItWorksSection/HowItWorksSection.jsx
Very minor change to the home page to make more room for the map preview.
> Adjustment to map preview container

- src/components/AddAdventureForm/AddAdventureForm.jsx
updated axios get request routes for dropdown data
> updated AddAdventureForm axios category GET requests

- src/components/UserPage/UserPage.jsx
Implements the UserPage with two sections fetching - recent & favorite adventures
> feat(UserPage): add user dashboard with recent & favorite adventures

- src/components/App/App.jsx
- src/components/EditAdventure/EditAdventureForm.jsx
- src/components/ViewDetails/ViewDetailsModal.jsx
check out the view detail modals please and thank you
> View details

- src/components/AddressSearch/AddressSearch.css
- src/components/BrowseAdventuresPage/BrowseAdventures.css
- src/components/BrowseAdventuresPage/BrowseAdventuresPage.jsx
Added css to the Browse Adventures Page (as well as to the search bar component to match). Almost done, other than the mystery blue bar slightly hiding under the navbar that I'm searching the origins of.
> Browse css

- src/components/App/App.jsx
This PR adds the new UserPage route to our frontend routing in App.jsx:
> feat(routes): add UserPage route to App.jsx

- src/components/AddAdventureForm/AddAdventureForm.jsx
Correction for data not being presented in the dropdown menus for categories, difficulty, and price. All are present now.
> Corrected issue with dropdown options not being presented when selected

- src/components/PendingAdventure/PendingAdventure.css
> feat(PendingAdventure): finalize admin‐page styling

- package.json
- server/modules/pool.js
- src/components/AddressSearch/AddressSearch.jsx
- src/components/AddressSearch/FavoriteButton/FavoriteButton.jsx
Added toggle for favorite button to AdventureCard - Database connection coming next
> Added toggle for favorite button to AdventureCard

- server/routes/adventure.router.js
- src/components/EditAdventure/EditAdventureForm.jsx
- updated backend PUT to fix NULL error
- updated EditAdventureForm to connect to backend
> updated edit adventure form and adventure PUT request

- src/components/EditAdventure/EditAdventureForm.css
- src/components/EditAdventure/EditAdventureForm.jsx
Hopefully added styling for the edit page, will be adjusted as needed!
> styling for edit form

- server/routes/adventure.router.js
- src/components/AdminPage/AdminPage.css
- src/components/AdminPage/AdminPage.jsx
- src/components/App/App.jsx
- src/components/PendingAdventure/PendingAdventure.jsx
updated adventure router and admin view
> updated admin page and adventure route

- src/components/AdminPage/AdminPage.css
- src/components/AdminPage/AdminPage.jsx
> Adjusted admin css

- server/routes/adventure.router.js
- src/components/AddressSearch/AddressSearch.jsx
- src/components/AddressSearch/FavoriteButton/FavoriteButton.jsx
Adventure.Router
-Added GET request to check favorite status of adventures to display correct filled in heart if already favorited
-Added DELETE request to allow users to un-favorite adventures by click the same filled in heart button if already favorited
FavoriteButton
-Added adventure status check axios request
-Added adventure favorite deletion axios request
-conditional heart button rendering so only logged in users can favorite adventures
-filled in heart will show if adventure is already favorited by specific user
-heart outline will show if logged in user has not yet favorited
> Favorite button functionality

- server/routes/adventure.router.js
- src/components/PendingAdventure/PendingAdventure.jsx
- src/components/RecentActivitySection/RecentActivitySection.css
- src/components/RecentActivitySection/RecentActivitySection.jsx
- src/components/UserPage/UserPage.css
- src/components/UserPage/UserPage.jsx
Updates
front-end:
- added image scaling to all areas where images are displayed
- updated spacing and styling for recent activity section
- added image url handling to all components following example in BrowseAdventuresPage
- fixed duplicate key error in UserPage
- updated spacing for UserPage My adventures and Favorite adventures
back-end:
- updated all backend GET routes in adventure.router to handle signed URLS for image handling
> Misc image scaling

- src/components/RecentActivitySection/RecentActivitySection.jsx
Correction for the BasicModal to include the joined data for category, price, and difficulty using a slice
> Basic Modal - Update to route and logic for pulling the three most recent with details included

- src/components/AddressSearch/AddressSearch.css
- src/components/AddressSearch/AddressSearch.jsx
- src/components/BasicModal/BasicModal.jsx
Location Services:
- Added user location collection with prompt for user to accept or deny
- Added initial search using user location
- Added user location marker on map
Radius Search:
- Added radius selection dropdown instead of slider to better fit the layout and styling of the page
IN PROGRESS:
- Still working on infoBox updates
- Adding visualized radius on map for a better user experience
> User location and radius updates

- src/components/AddAdventureForm/AddAdventureForm.jsx
Error Handling:
- Updated adventure image submission error handling for a better user experience.
- Added error handling in case user tries to type an address rather than select from the autocomplete options.
- Added success alert for visual confirmation.
Other:
- Cancel button now navigates user to home page.
> Adventure form updates

- originaldatabase.sql
- src/components/AboutUs/AboutUs.css
- src/components/AboutUs/AboutUs.jsx
- src/components/AddressSearch/AddressSearch.css
- src/components/AddressSearch/AddressSearch.jsx
- src/components/App/App.jsx
- src/components/BrowseAdventuresPage/BrowseAdventures.css
- src/components/ContactUs/ContactUs.css
- src/components/ContactUs/ContactUs.jsx
- src/components/Footer/Footer.jsx
- src/components/Nav/Nav.css
- src/index.css
**Browse Adventures Page**
- Styling responsiveness update
- Created a filters button to present the filters in a dropdown rather than across the search-container (Made it easier for smaller screen size)
- Reformatted the Browse Adventures page to work better with responsiveness. (Minimal Changes)
**Re-added newsletter database query** 
- Database query was re-added
**Made updates to the About Page (Working on that with new branch next)**
- Made it more condense, next will be working on aligning the information with what Matt has provided
> Browse Adventures Styling / re-added newsletter database query / Made updates to the About Page (Working on that with new branch next)

- server/routes/contact.router.js
- server/server.js
- src/components/AboutUs/AboutUs.css
- src/components/AboutUs/AboutUs.jsx
- src/components/ContactUs/ContactUs.jsx
**Contact Us Page Setup**
- ContactUs Page
- ContactUs css file
- contact.router.js
- contact router on server.js
**About Us Page Setup**
- AboutUs Component
- AboutUs.css file
> Contact Form (front-end and back-end ) / About Us Page (component and css)

- Procfile
- database.sql
- package.json
- server/modules/multer-S3-middleware.js
Here are some configuration updates to have Heroku work with our application:
- Added Procfile
- Update to original database.sql file to include the newsletter table and the contact table
- Updated package.json file
- Update to multer storage to seperate staging app images and production images that are stored in s3
> Heroku setup
